terraform {
  backend "gcs" {
    # Backend configuration is provided via backend.tfconfig file
    # This file is generated by setup-backend.sh or setup-backend.ps1
    # The bucket name follows the pattern: {project_id}-terraform-state
    
    # To set up:
    # 1. Run: ./setup-backend.sh (Linux/Mac) or .\setup-backend.ps1 (Windows)
    # 2. Or manually create backend.tfconfig with:
    #    bucket = "your-project-id-terraform-state"
    #    prefix = "time-api-gke/terraform.tfstate"
    #
    # Then initialize with: terraform init -backend-config=backend.tfconfig
  }
}

